# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yoon Tae Park
title: MS in Data Science @ NYU (Expected Graduation - May, 2023)
email: yp2201@nyu.edu
# email_title: Email (Email title override)
phone: (551) 280-6244
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  yoontaepark
linkedin_username: yoontaepark

# Google Analytics and Tag Manager
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-GJ4Z3SDN77"
    anonymize_ip         : # true, false (default)

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/14014507.jpg 
about_content: | # this will include new lines to allow paragraphs
  Hi my name is yoon. I'm a 2nd year MS student studying Data Science at NYU, and expected to graduate in May 2023.
  I'm actively looking for Data Scientist opportunities after graduation.
  
  I've started my Data Science career by leading a machine learning project in Samsung as a finance manager.
  As I wanted to learn more about data science, I'm now pursuing a master's degree in Data Science at NYU.
  For this summer, I did a data science internship at Walmart Global Tech, and built a m/l pipeline that solved problems in e-commerce. 

  My interests, broadly, are solving real world problems with data science, and I'm especially interested in NLP/NLU.
  Please refer to Project section to find out more. 

  My current skill set includes:

  - Language: Python(including pytorch/<a href="https://drive.google.com/file/d/1DdJniS3SKU--ZVSEezWZWgYtUx1QzdoM/view?usp=share_link">tensorflow</a>), SQL, PySpark

  - Tools: GCP, MS office, Tableau, Git/Github

  If you are interested, please contact me via email or linkedin.  

  Resume: <a href="https://drive.google.com/file/d/11MNm87WsSLTCXZgtHAihe3yQElIouoVR/view?usp=share_link">Resume_YoonTaePark.pdf</a>

### content section 
content:

  ### project section
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title:  Automated Judicial Case Briefing (mentored by World Bank)
        link: https://github.com/yoontaepark/capstone-oyez/blob/main/reports/final/Capstone_final_group41_project68.pdf
        link_text: Link) Automated Judicial Case Breifing 
        quote: >
          Creating a model that extracts relevant information from extremely long legal documents
        description: | # this will include new lines to allow paragraphs
          - Created a long legal document dataset through web scraping of US Supreme Court judicial cases

          - Developed a summary generation pipeline using SOTA models (BART, T5, and LED), resulting in a RougeL score 0.47

          - Implemented text extraction methods, such as TextRank, to improve the performance of the summarization model

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Dissecting Compositional Generalization (mentored by Faculty Fellow)
        link: https://github.com/yoontaepark/comp_gen_nlp/blob/main/reports/final/nlp_final_report_team_9.pdf
        link_text: Link) Dissecting Compositional Generalization
        quote: >
          Correlation Analysis on Generalization Capacities of Different Compositional Problems
        description: | # this will include new lines to allow paragraphs
          - Evaluated the accuracy of the model on 9 different compositional tasks, using 20 different initial weights
          
          - Built a codebase for a training evaluation pipeline, primarily used in the team’s research
          
          - Identified a positive correlation on certain tasks, providing evidence of compositional generalization capacity

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 2022 HUMANA/MAYS Healthcare Analytics Case Competition (top 10)
        link: https://github.com/yoontaepark/portfolio/blob/main/projects/Healthcare_analytics_case_competition.pdf
        link_text: Link) Healthcare Analytics Case Competition
        quote: >
          Identification of medicare members facing housing insecurity through predictive modeling and recommendations on how to help achieve there best health
        description: | # this will include new lines to allow paragraphs
          - Conducted EDA of medicare members facing housing insecuiry and segmented by three factors: Age, Region and Medical enviromnet

          - Bulit a model using lightGBM that showed 0.7573 ROC-AUC score in classifing medicare members facing insecurity issues

          - Suggested recommendations based on segmentations such as direct support on younger generations and government support on older generations        

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: A Toxicity Detection Dataset with r/WallStreetBet Comments
        link: https://github.com/yoontaepark/portfolio/blob/main/projects/Reddit_Toxicity_Dectection_Dataset.pdf
        link_text: Link) Toxicity Detection Dataset 
        quote: >
          Created a toxicity dataset from Reddit that can be used for any NLP/NLU research
        description: | # this will include new lines to allow paragraphs
          - Created a new toxicity detection dataset using comments from r/WallStreetBets and toxicity labels from Perspective API

          - Evaluated the dataset by comparing human baseline to current SOTA models: GPT-3, BERT, RoBERTa, and DeBERTa
 

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Collaborative-Filter Based Modeling for Movie Recommendation
        link: https://github.com/yoontaepark/portfolio/blob/main/projects/Movie_Recommendation_System.pdf
        link_text: Link) Movie Recommendation Model  
        quote: >
          Created a movie recommender model that suggests top 100 movies for each users
        description: | # this will include new lines to allow paragraphs
          - Created a recommender system using PySpark’s ALS method that provides top 100 movies for each user
          - Evaluated the model on Normalized Discounted Cumulative Gain (NDCG), and created a comparison to a single-machine implementation using LensKit
 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Citadel Fall 2021 Central Regional Datathon (1st place) - Tobacco usage data analysis
        link: https://github.com/yoontaepark/portfolio/blob/main/projects/Citadel_Fall_2021_Datation.pdf
        link_text: Link) Tobacco usage data analysis 
        quote: >
          Created a comprehensive analysis of Tobacco usage that improved MPOWER Effectiveness 
        description: | # this will include new lines to allow paragraphs
          - Generated geographic data visualizations that shows the pattern of tobacco usage in relation to MPOWER (WHO Framework Convention on Tobacco Control)
          - Built a regression model on tobacco usage using MPOWER and Geographic location


      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: NYU Center for Data Science - Graduate Student Analysis and Visualization
        link: https://github.com/yoontaepark/portfolio/blob/main/projects/Graduate_Student_Analysis.pdf
        link_text: Link) Graduate Student Analysis
        quote: >
          Created a comprehensive analysis of Graduate Students in NYU Data Science department 
        description: | # this will include new lines to allow paragraphs
          - Analyzed NYU data science past graduate students’ academic data to uncover distinct correlations
          - Visualized student academic performances and career outcomes by tableau that will assist prospective incoming students



  ### experience section
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Walmart Global Tech
        sub_title: Data Science Intern
        caption: May.2022 - Aug.2022
        # link: Link to company (optional)
        quote: >
          Worked in e-commerce team, leveraging rest of market data source to improve Walmart e-commerce platform
        description: | # this will include new lines to allow paragraphs
          - Created a benchmark dataset using rest of market and Walmart item information that enriched the team’s research
        
          - Proposed and implemented a boosting model using a benchmark dataset, resulting in a 35% improvement in the current category mapping performance
        
          - Deployed a machine learning pipeline to predict categories for new items, replacing the team's method

      - layout: left
        title: UNDP
        sub_title: Research Assistant
        caption: Dec. 2021 - Mar.2022
        # link: Link to company (optional)
        quote: >
          Worked as a research assistant in SDG(Sustainable Development Goals) AI Lab, contributing on Disaster Risk Reduction project.
        description: | # this will include new lines to allow paragraphs
          - Collaborated with Bilkent University to develop a model for safely routing people from an earthquake
        
          - Evaluated the reference risk of streets and suggested the safest path in Istanbul by calculating the total risk

      - layout: left
        title: Samsung Electronics
        sub_title: Machine Learning Project Lead
        caption: Oct. 2018 - Jun.2021
        # link: Link to company (optional)
        quote: >
          Elected as chair of automation projects for finance division that applies machine learning solutions.
        description: | # this will include new lines to allow paragraphs
          - Improved task accuracy from 60% to 95% through the application of Decision Tree and Naive Bayes methods

          - Identified problems and information on data structure and preprocessing and proposed categorization of input variables to prevent data overfitting
          
          - Analyzed and enhanced over six-hundred SAP finance programs on ABAP
          
          - Developed training materials and educated 300,000 employees, as well as over 100 foreign subsidiaries 
          
          - Integrated two separate systems on approval and expense management and established automated processes that eliminated inefficiency and directly connects with accounting system to reduce the number of approvals from 1.8 million to 1.2 million a year
          
          - Created a system that uses OCR technology to pull accounting information from vendor invoice
          
          - Built an automation scenario from invoice to accounting system and proposed learning methodologies for each field with a developer

      - layout: left
        title: 
        sub_title: Finance Manager 
        caption: Feb. 2014 - Oct.2018
        # link: Link to company (optional)
        quote: >
          Worked as a finance manager in Mobile division
        description: | # this will include new lines to allow paragraphs
          - Analyzed, investigated, and reported financial information of the mobile division in monthly closing of financial statements

          - Compared forecasts with actual data and added new benchmarks to save 20% in annual budget planning

          - Developed a chatbot that provides information on expense management and reimbursement in company intranet; used node.js and natural language processing and completed prototype production 

          - Managed facility investments of 8 overseas production plants, reviewed the investment plans and saved USD 730 million by comparing plans with executed investments and reallocating excessive investment budgets to future years

          - Lowered production cost per unit from USD 3.73/unit in 2015 to USD 3.43/unit in 2016, saving USD 240 million in total; analyzed yield and capacity utilization of the production plants and identified ways to boost productivity such as production re-scheduling and optimizing internal manufacturing cost

          - Won a prize in Samsung Electronics Hackathon 
            

  ### education section
  - title: Education
    layout: list
    content:
      - layout: left
        title: New York University
        sub_title: Master of Science in Data Science (GPA 3.95)
        caption: Expected Graduation) May 2023
        quote: >
          Studying foundation of data science, with the focus on NLP/NLU
        description: | # this will include new lines to allow paragraphs
          - Studying relevant courseworks such as Machine Learning, Big Data, Natural Language Understanding, and Time Series Forecasting

          - Working on various project that uses data science to solve real world problems. 
          
          - Currently working on two NLP/NLU projects. (One with World Bank, and one with Faculty Fellow)

      - layout: left
        title: Seoul National University
        sub_title: Bachelor of Arts in Business Administration
        caption: Graduated Feb. 2014
        quote: >
          Studied business administration, with the focus on finance 
        description: | # this will include new lines to allow paragraphs
          - Studied finance, marketing, accounting and calculus that had lots of team projects

          - Learned my key skills such as teamwork and working on a tight deadlines. 

          - A committee member of the SNU Finance Club (Team Leader) and SNU Mentoring Club (Vice President)


  ### others section
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I enjoy working on side projects/Datathon. I was recently placed <a href="https://drive.google.com/file/d/1Sdd6nYqAdtbQro4tvyHICAKGzm4m2q52/view?usp=share_link">1st place</a> at Citadel Regional Datathon.
      I am constantly participating on data challenges(including Kaggle), so contact me if you are interested in those challenges! 

      Outside of data science works, I enjoy traveling overseas and drinking coffee.

# Footer
footer_show_references: false
# references_title: 

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
